[package]
name = "rustadio"
version = "0.1.0"
authors = ["tango <cteters@pdx.edu>"]
edition = "2018"

[dependencies]
rodio = "0.9.0"
mime = "0.2.3"
rocket = "0.4.2"

iron = "0.5.1"
router = "0.5.1"
urlencoded = "0.5.0"
